### PR TITLE
Adding Finance.pm 

### PR DESCRIPTION
**Pull request by KinKaid666**
Finance.pm will allow users to access https://docs.developer.amazonservices.com/en_US/finances/Finances_Overview.html

### CODE REVIEW

**Comment by racke** [comment]
Looks good to me :+1:

**Comment by KinKaid666** [comment]
Thanks Rache.  Do I need to do anything?  I assume I don't have permissions
to accept the pull request to the master thread.

Eric

**Comment by racke** [comment]
I will pull it soon. Can I use your full name for authors/acknowledgements section?

**Comment by KinKaid666** [comment]
Yessir.

**Pull request merged**
